name: Update version
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          git config --global user.name 'Samuel Leroy'
          git config --global user.email '6c65726f79@users.noreply.github.com'
      - run: npm ci
      - run: npm version patch
        env:
          GITHUB_TOKEN: ${{ github.token }}